name: tests
on:
  pull_request:
  push:
    branches: [ main ]

  schedule:
  - cron: '25 08 * * *'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Homebrew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"
          echo "/home/linuxbrew/.linuxbrew/sbin" >> "$GITHUB_PATH"

      - name: Install test dependencies
        run: |
          brew tap bats-core/bats-core
          brew install bats-core bats-file bats-assert bats-support jq mkcert yq
          mkcert -install

      - name: Install DDEV (stable)
        if: matrix.ddev_version == 'stable'
        run: brew install ddev/ddev/ddev

      - name: Install DDEV (HEAD)
        if: matrix.ddev_version == 'HEAD'
        run: brew install --HEAD ddev/ddev/ddev

      - name: Download DDEV docker images
        run: ddev debug download-images

      - name: Run tests
        env:
          DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DDEV_NONINTERACTIVE: "true"
          DDEV_NO_INSTRUMENTATION: "true"
        run: bats tests --filter-tags '!release'
